### ISSUE TITLE
no lighting in the refraction

### ISSUE THREAD

**Issue by nbac** [shanecelis/water-demo#1]
You are not mentioning this in the BUGS but one major issue/ difference to the original demo is, that you don´t see lighting in the refraction / from above.

**Comment by Sithdown** [comment]
@nbac That can be solved easily.

Edit Water.shader so it includes the property `causticTex("Caustics", 2D) = "white" {}`

And remember to add the caustics RenderTexture on the inspector for the Water material.

Voila:
![image](https://user-images.githubusercontent.com/430612/52303036-3a7f6380-298f-11e9-8473-4b8c653195e0.png)

**Comment by shanecelis** [comment]
Thank you. Fix added in commit 4268259.
